version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000
    volumes:
      - ./src:/app/src
    depends_on:
      - mlflow

  mlflow:
    image: python:3.8-slim
    command: mlflow server --host 0.0.0.0 --port 5000
    ports:
      - "5000:5000"